# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: dev-mariadb
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: dev
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
      MARIADB_DATABASE: dev
    volumes:
      - mariadb:/var/lib/mysql
    networks: 
      - dev-mariadb
    ports:
      - 0.0.0.0:3306:3306

  adminer:
    container_name: dev-adminer
    image: adminer
    restart: always
    ports:
      - 0.0.0.0:8080:8080
    networks: 
      - dev-mariadb

volumes: 
  mariadb:

networks: 
  dev-mariadb: